### PR TITLE
fix: Adds hover support for web

### PR DESCRIPTION
**Pull request by soluchok**
Adds hover support for the web.
Issue https://github.com/google/charts/issues/410

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

**Comment by soluchok** [comment]
@mit-mit @nshahan pls take a look

**Comment by jaytyoung1** [comment]
Is this getting resolved?

**Comment by boganiLuca** [comment]
For completeness sake, it needs fixing on windows, also

**Comment by stuartmorgan-g** [comment]
This project is no longer maintained, and cannot accept any PRs. Community members interested in collaborating on a community-maintained fork can coordinate in [this issue](https://github.com/google/charts/issues/798).

**Pull request closed without merging**
