### PR TITLE
GitHub Sync

### PR DESCRIPTION
**Pull request by stuartmorgan**
This is an automatically generated pull request.

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Overriding CLA check for `noreply@` placeholder.

**Comment by stuartmorgan** [comment]
This temporarily uses a path-based dependency in charts_flutter; that will be removed once charts_common is published.

**Review by lorrainekan — APPROVED** [review]

**Comment by fpatron** [comment]
Hi,
I've got an error since your update, could you fix it? Thanks !

Running "flutter pub get" in kandixi_flutter...                 
Error on line 18, column 11: Invalid description in the "charts_flutter" pubspec on the "charts_common" dependency: "../charts_common/" is a relative path, but this isn't a local pubspec.

**Comment by stuartmorgan** [comment]
> Error on line 18, column 11: Invalid description in the "charts_flutter" pubspec on the "charts_common" dependency: "../charts_common/" is a relative path, but this isn't a local pubspec.

Please read the comment directly above yours; removing that shortly was already planned.

The only way to have that error is if you are trying to use the latest commit via a git reference; the solution is not to do that, as this particular commit isn't intended for external use.

**Pull request merged**
