### PR TITLE
BarLabel Decorator cosniders TextDirection

### PR DESCRIPTION
**Pull request by AITechNassim**
Computing the labelX by taking into consideration the TextDirection

### CODE REVIEW

**Comment by AITechNassim** [comment]
@googlebot I signed it!

**Comment by winksaville** [comment]
@AITechNassim,

Hello, I want to start off by saying that I'm not associated with Charts, except that I've used it, found an issue, devised a found solution and I created a [pull request](https://github.com/google/charts/pull/457). But as it says at the bottom of the [README.md](https://github.com/google/charts/blob/master/README.md) of this repo, nothing happened:

"This project is developed internally at Google and published for external consumption, external contributions unfortunately cannot be taken at this time."

Since I like what I've seen so far with Flutter, Charts and the [Dart community](https://gitter.im/dart-lang/TALK-general) I decided to  create a "community supported" fork of Charts. We are accepting PR's, please consider porting this PR to https://github.com/exafree/charts_cf

Thanks,

Wink

**Comment by AITechNassim** [comment]
Thanks for the info. Done.
> 
> 
> @AITechNassim,
> 
> Hello, I want to start off by saying that I'm not associated with Charts, except that I've used it, found an issue, devised a found solution and I created a [pull request](https://github.com/google/charts/pull/457). But as it says at the bottom of the [README.md](https://github.com/google/charts/blob/master/README.md) of this repo, nothing happened:
> 
> "This project is developed internally at Google and published for external consumption, external contributions unfortunately cannot be taken at this time."
> 
> Since I like what I've seen so far with Flutter, Charts and the [Dart community](https://gitter.im/dart-lang/TALK-general) I decided to create a "community supported" fork of Charts. We are accepting PR's, please consider porting this PR to https://github.com/exafree/charts_cf
> 
> Thanks,
> 
> Wink

**Comment by stuartmorgan-g** [comment]
This project is no longer maintained, and cannot accept any PRs. Community members interested in collaborating on a community-maintained fork can coordinate in [this issue](https://github.com/google/charts/issues/798).

**Pull request closed without merging**
