### PR TITLE
with compile works for flutter3.0

### PR DESCRIPTION
**Pull request by joyhope**
only version update for easy to run the sample in the simulator. Otherwise the original project is unable to run now.

### CODE REVIEW

**Comment by joyhope** [comment]
The fixed type will make sample "selection line highlight custom shape works"

**Comment by joyhope** [comment]
I recommit, the sample case is working now.

**Comment by joyhope** [comment]
More unworkable samples are worked. It all caused a type cast problem.  I changed the type define according to the error report. It just works.

**Comment by crizant** [comment]
Seems Google is giving up this repo, every time a new flutter version comes out, this repo lags behind for months.
Do you think we should fork it and publish another version to pub.dev? 
No new features, just simple fixes of incompatibility with the latest flutter versions. It should relieve the pain of fellow developers.

**Comment by joyhope** [comment]
I agree with this idea, but I am not sure whether it is proper.  I begin to add features but it seems no hope to merge in this repo. If anyone makes a start, I like to follow. I think the chart is an important library to use.

**Comment by joyhope** [comment]
I  add chart_flutter/util/monotonex.dart , add smoth line to the chart. 
Screenshot from 2022-05-20 22-28-20

the chart line is smooth.  but I am not sure whether this will be merged.

**Comment by crizant** [comment]
> I add chart_flutter/util/monotonex.dart , add smoth line to the chart. Screenshot from 2022-05-20 22-28-20
> 
> the chart line is smooth. but I am not sure whether this will be merged.

Even if it got merged finally, it will be 2 months later.
E.g. Flutter 2.2 null safety is released in May 2021, and the null safety fix of this library is released in July 2021.

**Comment by mark-dropbear** [comment]
@stuartmorgan is this a topic you might be able to provide any kind of insight on. I know public support isn't the key goal of the repo but just as a way of being able to set some expectations and if there is a timeline to add Flutter 3 support?

**Comment by OnesWYong** [comment]
> I add chart_flutter/util/monotonex.dart , add smoth line to the chart. Screenshot from 2022-05-20 22-28-20
> 
> the chart line is smooth. but I am not sure whether this will be merged.

How should I implement support area chart

**Comment by stuartmorgan-g** [comment]
This project is no longer maintained, and cannot accept any PRs. Community members interested in collaborating on a community-maintained fork can coordinate in [this issue](https://github.com/google/charts/issues/798).

**Pull request closed without merging**
