### PR TITLE
fix pie chart for single items

### PR DESCRIPTION
**Pull request by SaschaZ**
This commit fix the pie chart if it has only one item which would result in a circle with a full range of 2 times PI or more. To solve this the complete circle range is limited to 2 times PI minus 0.001 time PI.

### CODE REVIEW

**Comment by SaschaZ** [comment]
CLA signed.

**Comment by sjmcdowall** [comment]
Well I certainly hope this gets merged soon.. Why does it take 2+ MONTHS to get a fix like this in?

**Comment by lorrainekan** [comment]
Fixed in this commit:
https://github.com/google/charts/pull/154/commits/d0db5f174044ed5fe293e8fa1550e9cfdda5a79c

**Comment by sjmcdowall** [comment]
@lorrainekan  -- I am confused by this.  Is the commit merged into master and pushed because I do "flutter upgrade" often and this still is an issue as of today..

**Pull request closed without merging**
