### PR TITLE
Loosen intl dependency

### PR DESCRIPTION
**Pull request by cbenhagen**
Needed due to https://github.com/flutter/flutter/pull/39932

### CODE REVIEW

**Comment by Joran-Dob** [comment]
We need this loosing of dependency requirements, as we cannot build right now from the pub version due to version resolving issues. 😱

**Comment by cbenhagen** [comment]
@Joran-Dob you can add this to your `pubspec.yaml`:
```yaml
dependency_overrides:
  intl: ^0.16.0
```

**Comment by Eimji** [comment]
> @Joran-Dob you can add this to your `pubspec.yaml`:
> 
> ```yaml
> dependency_overrides:
>   intl: ^0.16.0
> ```

I think the best option is to simply put intl: without specifying the version in pubspec.yaml

**Comment by Joran-Dob** [comment]
> @Joran-Dob you can add this to your `pubspec.yaml`:
> 
> ```yaml
> dependency_overrides:
>   intl: ^0.16.0
> ```

Thanks, @cbenhagen, we already added this. But it would probably be nice if we can remove the override.

**Comment by lorrainekan** [comment]
Widened up the intl dependency in the latest push.

**Pull request closed without merging**
